### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by alashow** [xiprox/ErrorView#10]
Hey. Very handy library, thanks!

Are you going to refactor the project to AndroidX?
Or use Material Components for the retry button?

Will you accept a PR for this?

**Comment by alashow** [comment]
Oh, I just remembered I can just override the layout file to override default views.

**Comment by xiprox** [comment]
Hey! Glad you like the library.

Why would we use AndroidX though? We don't depend on anything that's now shipped under X. We do use the support libs in the sample app, but currently I don't think migrating is necessary there.

So yeah, if you are looking to completely change the views, overriding the layout is the way to go. 👍

**Comment by alashow** [comment]
I had to fork it anyways.
As you were overriding retry button's background resource in `ErrorView`.

**Comment by xiprox** [comment]
Oh, that's right.

Are you considering a reusable solution or a specific internal fork?

**Comment by alashow** [comment]
> Why would we use AndroidX though? We don't depend on anything that's now shipped under X. 

Thought this library depends on AppCompat, hence the suggestion. My bad :)

> Are you considering a reusable solution or a specific internal fork?

My end goal was to have a button themed with material components, which looks better and will be consistent with other buttons in my app. This small [change](https://github.com/alashow/ErrorView/commit/aa87d2d9aea7a7a7b92376070aadabde0af6d5c7) did the job.


I'm not sure if anyone will need this, but if they do, this changes would help to avoid a fork:
- No overriding background resource in ErrorView if custom background wasn't set via theme or else (only depend on defined background in layout file)
- Optional: Change Retry button view from `TextView` to `Button` and option to apply custom theme/style to the retry button.
