### ISSUE TITLE
Double inflated LinearLayout in ErrorView

### ISSUE THREAD

**Issue by pbednarz** [xiprox/ErrorView#2]
Hi, great library, but I have noticed that ErrorView is extending LinearLayout but it is also inflating xml layout with also defined LinearLayout instance. XML layout should instead use `<merge>` tag.

http://trickyandroid.com/protip-inflating-layout-for-your-custom-view/

**Comment by xiprox** [comment]
Hello,

I was going to fix this today but I see that you've already made the changes on your fork. Would you mind submitting a pull request instead? It would be great if you could break your changes down into different commits though. You could do something like `git reset --soft 8a55fc6` and have commits like `Update gradle, sdk, and appcompat versions`, `Make it possible to style ErrorView in the app theme`, and `Remove double instances of LinearLayout`. You don't have to keep the color changes. I'll be changing them myself later anyways.

Thank you for your contribution.

**Comment by pbednarz** [comment]
Pull Request  #3 is ready. I didn't change colors in pull request as requested. Pretty simple and useful library you have made - great idea! :)

**Comment by xiprox** [comment]
Thanks.
