### ISSUE TITLE
Unable to set subtitle text alignment

### ISSUE THREAD

**Issue by julioz** [xiprox/ErrorView#4]
I'm trying to set a subtitle message that goes longer than one line of text.
The text then gets wrapped to more lines, but by default they are left aligned. Is there a way to set the text alignment to center that I may not be aware of?

**Comment by xiprox** [comment]
I've pushed a new (`2.1.0`) version to maven. You should be able to use it in the following hours. Good luck!

**Comment by julioz** [comment]
Wow, that is great, thank you so much. I was ready to prepare my pull request but I'm glad the library has an active maintainer.
I'll test that as soon as possible.

Just as a thought, I think maybe that could be an accessible property - I feel like most of the time people would want centered subtitles but I also think it'd be nice to let them set differently if they need to. WDYT?

**Comment by xiprox** [comment]
No issue. You found a time I had almost nothing to do to create the issue. The fix being a small one also helped.

Hmm. I'll add that in too, but I'm not sure how long it will take me. If you prepare a PR in the meantime, I'll merge it.
