### ISSUE TITLE
Sample app crashed on Android 6.0

### ISSUE THREAD

**Issue by slmyldz** [xiprox/ErrorView#5]
Device: Nexus 5

10-05 09:55:44.974 28433-28433/? E/AndroidRuntime: java.lang.LinkageError: tr.xip.errorview.sample.MainActivity
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at dalvik.system.DexFile.defineClassNative(Native Method)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at dalvik.system.DexFile.defineClass(DexFile.java:226)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at dalvik.system.DexPathList.findClass(DexPathList.java:338)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-05 09:55:44.974 28433-28433/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by xiprox** [comment]
Hello,

I don't own a device that can be upgraded to Android 6.0 yet, so I'll need you to see if it's fixed. Please try this apk file: http://puu.sh/kzqvX/be4f55e455.apk

**Comment by slmyldz** [comment]
Hello @xiprox ,
It is working perfect :100:

**Comment by xiprox** [comment]
Ok, thanks for the feedback. I'll be pushing the fix shortly.

**Comment by zhanglirongkevin** [comment]
Hi xiprox,
My app have the same bug. Can you tell me how to fix this crash bug on Android 6.0?

**Comment by xiprox** [comment]
See the Activity that throws the error. There should be a method that was added to the Activity class in Android 6 that clashes with the one in your code. In my case, I had a helper method `getColor(int)` which was added by default on Android 6. These clashed causing the above error to be thrown.

Relevant commit: 209c5d2

**Comment by zhanglirongkevin** [comment]
I  find it Tks. I have a getColor method too. but when i fix this, still crash. I guess i have other conflict method.
