### ISSUE TITLE
Make it possible to change error image visibility

### ISSUE THREAD

**Issue by Rainer-Lang** [xiprox/ErrorView#6]
Add the necessary methods and attributes in order to make it possible to set and toggle the error image's visibility.

**Comment by Rainer-Lang** [comment]
great lib btw :-)

**Comment by xiprox** [comment]
Thanks :)

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by xiprox** [comment]
Unfortunately, no.

Now that I think about it though, as a temporary solution, you can do:
````java
ImageView errorImage = (ImageView) mErrorView.findViewById(R.id.error_image);
errorImage.setVisibility(...);
```

**Comment by xiprox** [comment]
Totally not late, but this is now supported with v3.0.0.
